name: Build Cart-Flasher

on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-latest
    env:
      BLOCKSDS: /opt/wonderful/thirdparty/blocksds/core
    name: Build with BlocksDS toolchain using official Docker image
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Build app
        id: build
        run: |
          make CART_FLASHER_COMMIT=$(echo "${{ github.sha }}" | cut -c1-7) CART_FLASHER_VERSION=nightly
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v6
        with:
          path: cart_flasher-nightly.nds
          name: cart_flasher-nightly
