name: Build Cart-Flasher release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:20230622
    name: Build with stable devkitARM using official Docker image
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Build app
        id: build
        run: |
          make CART_FLASHER_COMMIT=${{ github.ref_name }}
      - name: Upload cart_flasher.nds
        uses: AButler/upload-release-assets@v2.0
        with:
          files: cart_flasher-*.nds
          repo-token: ${{ secrets.GITHUB_TOKEN }}
